CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.{TABLE_NAME}(
   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
   payload_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.payloads(id),
   config_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.agent_config(id) ON DELETE RESTRICT,
   name VARCHAR(255) UNIQUE NOT NULL,
   note TEXT,
   status VARCHAR(50) NOT NULL,
   first_callback TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   last_callback TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   modified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);