CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.{TABLE_NAME}(
   id UUID PRIMARY KEY NOT NULL,
   name VARCHAR(255) NOT NULL,
   note TEXT NOT NULL,
   status VARCHAR(50) NOT NULL,
   first_callback TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   last_callback TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   modified_at TIMESTAMPTZ DEFAULT NULL
);
