CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_task(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   type TEXT NOT NULL,
   status VARCHAR(255) NOT NULL,
   MODULE VARCHAR(255) NOT NULL,
   command VARCHAR(255) NOT NULL,
   created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   started TIMESTAMPTZ DEFAULT NULL,
   finished TIMESTAMPTZ DEFAULT NULL,

   CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);