CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_info(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   host_name VARCHAR(255) NOT NULL,
   ip_address VARCHAR(100) NOT NULL,
   user_name VARCHAR(255) NOT NULL,
   system_info TEXT NOT NULL,
   os_info TEXT NOT NULL,

   CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);