CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.{TABLE_NAME} (
    task_id UUID PRIMARY KEY,
    agent_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.agents(id),
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    module VARCHAR(255),
    command JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    FOREIGN KEY (agent_id) REFERENCES {POSTGRES_SCHEMA}.agents(id) ON DELETE CASCADE
);
