CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.{TABLE_NAME}(
   id UUID PRIMARY KEY NOT NULL,
   name VARCHAR(255) NOT NULL,
   note TEXT NOT NULL,
   first_callback TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   last_callback TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
   modified_at TIMESTAMPTZ DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_info(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   host_name VARCHAR(255) NOT NULL,
   ip_address VARCHAR(100) NOT NULL,
   user_name VARCHAR(255) NOT NULL,
   system_info TEXT NOT NULL,
   os_info TEXT NOT NULL,

  CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_config(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   callback_urls TEXT[] NOT NULL,
   rotation_type VARCHAR(255) NOT NULL,
   rotation_retries INTEGER NOT NULL,
   sleep INTEGER NOT NULL,
   jitter INTEGER NOT NULL,
   start_date TIMESTAMPTZ NOT NULL,
   kill_date TIMESTAMPTZ NOT NULL,
   working_hours INTEGER[] NOT NULL,
   headers TEXT[] NOT NULL,

   CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_task(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   type TEXT NOT NULL,
   status VARCHAR(255) NOT NULL,
   MODULE VARCHAR(255) NOT NULL,
   command VARCHAR(255) NOT NULL,
   created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
   started TIMESTAMPTZ DEFAULT NULL,
   finished TIMESTAMPTZ DEFAULT NULL,

   CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.agent_command(
   id BIGSERIAL PRIMARY KEY,
   agent_id UUID NOT NULL,
   name VARCHAR(255) NOT NULL,
   started TIMESTAMPTZ DEFAULT NULL,
   completed TIMESTAMPTZ DEFAULT NULL,
   parameters TEXT[] NOT NULL,
   output TEXT NOT NULL,

   CONSTRAINT fk_agent FOREIGN KEY(agent_id) REFERENCES {POSTGRES_SCHEMA}.{TABLE_NAME}(id) ON DELETE CASCADE
);
