CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.{TABLE_NAME}(
    id UUID PRIMARY KEY,
    listener_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.listeners(id),
    config_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.agent_config(id),
    name VARCHAR(255) NOT NULL,
    arch VARCHAR(50) NOT NULL,
    public_key BYTEA NOT NULL,
    private_key BYTEA NOT NULL,
    token UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);