CREATE TABLE IF NOT EXISTS {POSTGRES_SCHEMA}.team_members (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    team_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.teams(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES {POSTGRES_SCHEMA}.users(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);