CREATE TABLE IF NOT EXISTS {DB_SCHEMA_NAME}.{TABLE_NAME} (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    pw_hash TEXT NOT NULL,
    role_id INT NOT NULL REFERENCES roles(id)
    created_ts TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_ts TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
