name: GoTests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21.x' ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run handler tests
      run: go test -v ./tests/handlers/...
