name: Go Tests

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: 
          - "1.20"
          - "1.21"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      working-directory: ./teamserver
      run: go mod download

    - name: Run handler tests
      working-directory: ./teamserver
      run: go test -v ./teamserver/tests/handlers/...
